name: Terraform CD

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch
  pull_request:
    branches:
      - main  # Trigger deployment on PR to main branch

jobs:
  terraform:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.6  # Specify the version you need

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Replace with your actual AWS region
          audience: sts.amazonaws.com
        env:
          AWS_REGION: us-east-2  # Replace with your actual AWS region
          ECR_REPOSITORY: MY_ECR_REPOSITORY
          ECS_SERVICE: MY_ECS_SERVICE
          ECS_CLUSTER: MY_ECS_CLUSTER
          ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION
          CONTAINER_NAME: MY_CONTAINER_NAME

      - name: Initialize Terraform
        run: |
          cd terraform  # Change directory into the terraform folder
          terraform init

      - name: Plan Terraform
        run: |
          cd terraform  # Change directory into the terraform folder
          terraform plan -input=false -out=tfplan

      - name: Apply Terraform
        run: |
          cd terraform  # Change directory into the terraform folder
          terraform apply -auto-approve tfplan
