name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Deploy using Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6  # Specify the version you need

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Replace with your actual AWS region

      - name: Initialize Terraform
        run: |
          terraform init helloworldnodeapp/.github/workflows  # Initialize Terraform in the directory with main.tf

      - name: Validate Terraform Configuration
        run: |
          terraform validate helloworldnodeapp/.github/workflows  # Validate the Terraform configuration

      - name: Plan Terraform Deployment
        run: |
          terraform plan -input=false -out=tfplan helloworldnodeapp/.github/workflows  # Generate Terraform execution plan

      - name: Apply Terraform Changes
        run: |
          terraform apply -auto-approve tfplan helloworldnodeapp/.github/workflows  # Apply Terraform changes

      # Optionally, add more steps here for testing or other tasks

      - name: Show Terraform State
        run: |
          terraform show helloworldnodeapp/.github/workflows  # Show Terraform state

      # Optionally, add cleanup steps if needed

      - name: Cleanup Terraform
        run: |
          terraform destroy -auto-approve helloworldnodeapp/.github/workflows  # Destroy resources managed by Terraform
